<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Equipment.Data\Equipment.Data.csproj" />
      <ProjectReference Include="..\Equipment.Domain\Equipment.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NPOI" Version="2.7.5" />
    </ItemGroup>

</Project>
